### ISSUE TITLE
Cannot run on Windows

### ISSUE THREAD

**Issue by fennelhans** [shkcodes/dynamic_config_generator#3]
When trying to run on Windows, I get the following error:

```
'config_builder' is not recognized as an internal or external command,
operable program or batch file.
```

My command is `flutter packages pub run build_runner build --define 'dynamic_config_generator|config_builder=variant=stable'`

My pubspec has `dynamic_config_generator: ^0.3.2` under dev_dependencies.

**Comment by fennelhans** [comment]
Thanks for taking a look. Let me know if you need anything from my end.

**Comment by shkcodes** [comment]
Sorry for the late reply but I wasn't able to reproduce this. Will try again on a different Windows machine.

**Comment by shkcodes** [comment]
Hey @fennelhans, are you still facing this issue?

**Comment by hanskokx** [comment]
Sadly, it's no longer @fennelhans 😓
I'll double check when I get back home.

**Comment by hanskokx** [comment]
Yes, I still see this issue

**Comment by hanskokx** [comment]
Do you lack proper access to a Windows development environment? How can I help?

**Comment by shkcodes** [comment]
@hanskokx can you please try running this `
flutter packages pub run build_runner build --define """dynamic_config_generator|config_builder=variant=$debug"""`. You needed to escape the inverted commas on Windows.

**Comment by hanskokx** [comment]
Yeah, you're right. That does the trick. Maybe we can make a note of this in the README?

**Comment by shkcodes** [comment]
yep, I will update the README, thanks!
