### ISSUE TITLE
Incompatible with Flutter 3.11

### ISSUE THREAD

**Issue by fennelhans** [shkcodes/dynamic_config_generator#4]
```
$ flutter pub upgrade
Downloading package sky_engine...                                  583ms
Downloading flutter_patched_sdk tools...                           509ms
Downloading flutter_patched_sdk_product tools...                   407ms
Downloading darwin-arm64 tools...                                   4.3s
Downloading darwin-arm64/font-subset tools...                      306ms
Resolving dependencies... (3.4s)
The current Dart SDK version is 3.1.0-87.0.dev.

Because fennel depends on dynamic_config_generator >=0.0.2 which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.1.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
```

**Comment by harshhhh15** [comment]
The error message is indicating that one of your dependencies, `fennel`, has a dependency on `dynamic_config_generator` that does not support null safety. As a result, version solving has failed.

To fix this issue, you can try updating your `pubspec.yaml` file to specify a version of `dynamic_config_generator` that does support null safety. You can check the `dynamic_config_generator` package page on Pub.dev to see which version(s) support null safety.

Alternatively, you can try downgrading the version of `fennel` to a version that does not have a dependency on `dynamic_config_generator`, or you can contact the package author to ask for support for null safety.

**Comment by fennelhans** [comment]
> The error message is indicating that one of your dependencies, `fennel`, has a dependency on `dynamic_config_generator` that does not support null safety. As a result, version solving has failed.
> 
> To fix this issue, you can try updating your `pubspec.yaml` file to specify a version of `dynamic_config_generator` that does support null safety. You can check the `dynamic_config_generator` package page on Pub.dev to see which version(s) support null safety.
> 
> Alternatively, you can try downgrading the version of `fennel` to a version that does not have a dependency on `dynamic_config_generator`, or you can contact the package author to ask for support for null safety.

Yes, I am the author of `fennel`. I am not incorrect in this.

![image](https://github.com/shkcodes/dynamic_config_generator/assets/98828887/94c3d707-17e8-4507-b73b-15cee2a4d468)

**Comment by fennelhans** [comment]
If you approve my pull request, the issue will be resolved. (Although, you'll also want to bump the version number, I'm sure.)

https://github.com/shkcodes/dynamic_config_generator/pull/5

**Comment by shkcodes** [comment]
Release 0.4.0
